"""Initial migration.

Revision ID: 40ab036f9e6d
Revises: 
Create Date: 2023-05-18 04:29:35.221253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40ab036f9e6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marca',
    sa.Column('cod_marca', sa.Integer(), nullable=False),
    sa.Column('referencia_marca', sa.Integer(), nullable=True),
    sa.Column('nome_marca', sa.String(length=100), nullable=False),
    sa.Column('data_alterado', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('cod_marca'),
    schema='vtex'
    )
    op.create_table('precos',
    sa.Column('cod_preco', sa.Integer(), nullable=False),
    sa.Column('novo_preco', sa.Float(), nullable=True),
    sa.Column('preco', sa.Float(), nullable=True),
    sa.Column('preco_base', sa.Float(), nullable=True),
    sa.Column('skuid', sa.Integer(), nullable=True),
    sa.Column('cod_marca', sa.Integer(), nullable=True),
    sa.Column('trade_policy', sa.Integer(), nullable=True),
    sa.Column('cnt', sa.Integer(), nullable=True),
    sa.Column('canal_venda_porcentagem', sa.Integer(), nullable=True),
    sa.Column('custo_envio', sa.Float(), nullable=True),
    sa.Column('preco_final', sa.Float(), nullable=True),
    sa.Column('cod_produto', sa.Integer(), nullable=True),
    sa.Column('data_alterado', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('cod_preco'),
    schema='vtex'
    )
    op.create_table('produto',
    sa.Column('cod_produto', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=False),
    sa.Column('nome_produto', sa.String(length=500), nullable=False),
    sa.Column('preco_lista', sa.Float(), nullable=True),
    sa.Column('preco', sa.Float(), nullable=True),
    sa.Column('base_preco', sa.Float(), nullable=True),
    sa.Column('ref_marca', sa.Integer(), nullable=True),
    sa.Column('trade_policy', sa.Integer(), nullable=True),
    sa.Column('skuid', sa.Integer(), nullable=True),
    sa.Column('id_listapreco', sa.Integer(), nullable=True),
    sa.Column('canal_venda', sa.Integer(), nullable=True),
    sa.Column('cod_marca', sa.Integer(), nullable=True),
    sa.Column('data_alterado', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('cod_produto'),
    schema='vtex'
    )
    op.create_table('usuario',
    sa.Column('cod_usuario', sa.Integer(), nullable=False),
    sa.Column('senha', sa.String(length=100), nullable=False),
    sa.Column('nome_usuario', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('data_alterado', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('cod_usuario'),
    schema='vtex'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario', schema='vtex')
    op.drop_table('produto', schema='vtex')
    op.drop_table('precos', schema='vtex')
    op.drop_table('marca', schema='vtex')
    # ### end Alembic commands ###
